src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\UniqueConstraint(name: 'UNIQ_IDENTIFIER_EMAIL', fields: ['email'])]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180)]
    private ?string $email = null;

    /**
     * @var list<string> The user roles
     */
    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    /**
     * @var Collection<int, Persona>
     */
    #[ORM\OneToMany(targetEntity: Persona::class, mappedBy: 'user')]
    private Collection $personas;

    #[ORM\Column]
    private ?bool $temp_pass = null;

    /**
     * @var Collection<int, Cambios>
     */
    #[ORM\OneToMany(targetEntity: Cambios::class, mappedBy: 'user', orphanRemoval: true)]
    private Collection $cambios;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $created_time = null;

    public function __construct()
    {
        $this->created_time = new \DateTime();
        $this->personas = new ArrayCollection();
        $this->cambios = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     *
     * @return list<string>
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    /**
     * @param list<string> $roles
     */
    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    /**
     * @return Collection<int, Persona>
     */
    public function getPersonas(): Collection
    {
        return $this->personas;
    }

    public function addPersona(Persona $persona): static
    {
        if (!$this->personas->contains($persona)) {
            $this->personas->add($persona);
            $persona->setUser($this);
        }

        return $this;
    }

    public function removePersona(Persona $persona): static
    {
        if ($this->personas->removeElement($persona)) {
            // set the owning side to null (unless already changed)
            if ($persona->getUser() === $this) {
                $persona->setUser(null);
            }
        }

        return $this;
    }

    public function isTempPass(): ?bool
    {
        return $this->temp_pass;
    }

    public function setTempPass(bool $temp_pass): static
    {
        $this->temp_pass = $temp_pass;

        return $this;
    }

    /**
     * @return Collection<int, Cambios>
     */
    public function getCambios(): Collection
    {
        return $this->cambios;
    }

    public function addCambio(Cambios $cambio): static
    {
        if (!$this->cambios->contains($cambio)) {
            $this->cambios->add($cambio);
            $cambio->setUser($this);
        }

        return $this;
    }

    public function removeCambio(Cambios $cambio): static
    {
        if ($this->cambios->removeElement($cambio)) {
            // set the owning side to null (unless already changed)
            if ($cambio->getUser() === $this) {
                $cambio->setUser(null);
            }
        }

        return $this;
    }

    public function getCreatedTime(): ?\DateTimeInterface
    {
        return $this->created_time;
    }

    public function setCreatedTime(\DateTimeInterface $created_time): static
    {
        $this->created_time = $created_time;

        return $this;
    }
}

src/Controller/ProfileController.php
<?php

namespace App\Controller;

use App\Entity\Cambios;
use App\Entity\User;
use App\Services\Helpers;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

class ProfileController extends AbstractController
{
    #[Route('/perfil', name: 'app_profile')]
    public function index(EntityManagerInterface $em): Response
    {
        $asistentes_tabla = [];
        $repoUser = $em->getRepository(User::class);

        if($this->isGranted('ROLE_ADMIN')) {
            $all_users = $repoUser->findAll();
        } else {
            $all_users = [$this->getUser()];
        }

        foreach ($all_users as $user) {
            foreach ($user->getPersonas() as $i => $persona) {
                $datos_user = [];
                $datos_user['mail'] = $user->getEmail();
                $datos_user['nombre'] = $persona->getNombreCompleto();
                $datos_user['alergias'] = $persona->getAlergias();
                $datos_user['mesa'] = $persona->getMesaPreferencia();
                $datos_user['status'] = $persona->getStatus();
                $asistentes_tabla[] = $datos_user;
            }
        }

        return $this->render('profile/index.html.twig', [
            'asistentes_tabla' => $asistentes_tabla
        ]);
    }

    #[Route('/ajax/pedir_cambio', name: 'app_profile_pedir_cambio')]
    public function ajaxPedirCambios(EntityManagerInterface $em): JsonResponse
    {
        $status = false;
        $msg = 'error';

        $respuestas = array_map([Helpers::class, 'sanitizeTextField'], $_POST);

        if (isset($respuestas['modificacion'])) {
            $user = $this->getUser();
            if ($user != null) {
                $cambio = new Cambios();
                $cambio->setUser($user);
                $cambio->setTexto($respuestas['modificacion']);
                $em->persist($cambio);
                $em->flush();

                foreach ($user->getPersonas() as $i => $persona) {
                    $persona->setStatus('cambio');
                    $em->persist($persona);
                    $em->flush();
                }

                $status = true;
                $msg = 'creado|'.$cambio->getId();
            }
        }

        return new JsonResponse([
            'status' => $status,
            'msg' => $msg,
        ]);
    }
}

templates/profile/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Bienvenido a tu perfil{% endblock %}

{% block body %}
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8">
            <div class="text-center mt-5">
                <div class="card form-container p-4 mt-5">
                    <h2>Acá puedes cambiar tu contraseña y pedir un cambio a tus datos del matrimonio.</h2>
                    <div class="row">
                        <div class="col-12 text-center">
                            Correo: <b>{{ app.user.email }}</b>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-12 text-center">
                            <button class="btn btn-primary mt-3" type="button" data-bs-toggle="modal" data-bs-target="#cambiar_contra_modal">
                                Cambiar Contraseña {{ ux_icon('ph:password', {height: '16px', width: '16px', 'aria-hidden': true}) }}
                            </button>
                        </div>
                        <div class="col-12 text-center">
                            <button class="btn btn-warning mt-3" type="button" data-bs-toggle="modal" data-bs-target="#pedir_cambios_modal">
                                Pedir Cambios {{ ux_icon('ph:list-magnifying-glass', {height: '16px', width: '16px', 'aria-hidden': true}) }}
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-2"></div>
    </div>
    {% if asistentes_tabla|length > 0 %}
        <div class="row mt-3">
            <div class="col-md-2"></div>
            <div class="col-md-8">
                {% if is_granted('ROLE_ADMIN') %}
                    <h3>Tabla de asistentes</h3>
                {% else %}
                    <h3>Tu información</h3>
                {% endif %}
                <table class="table table-sm table-striped table-hover">
                    <thead>
                        <tr>
                            {% if is_granted('ROLE_ADMIN') %}
                                <th>Email</th>
                            {% endif %}
                            <th>Nombre</th>
                            <th>Alimentos</th>
                            <th>Preferencia Mesa</th>
                            {% if is_granted('ROLE_ADMIN') %}
                                <th></th>
                            {% endif %}
                        </tr>
                    </thead>
                    <tbody>
                        {% for asistente in asistentes_tabla %}
                            <tr class="{% if is_granted('ROLE_ADMIN') %}{% if asistente.status == 'cambio' %}table-warning{% elseif asistente.status == 'confirmado' %}table-success{% elseif asistente.status == 'rechazado' %}table-danger{% endif %}{% endif %}">
                                {% if is_granted('ROLE_ADMIN') %}
                                    <td>{{ asistente.mail }}</td>
                                {% endif %}
                                <td>{{ asistente.nombre }}</td>
                                <td>{{ asistente.alergias }}</td>
                                <td>{{ asistente.mesa }}</td>
                                {% if is_granted('ROLE_ADMIN') %}
                                    <td></td>
                                {% endif %}
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="col-md-2"></div>
        </div>
    {% endif %}
{% endblock %}
{% block javascripts %}
    <script type="module">
        $( document ).ready(function() {
            $(document).find("#form_cambiar_contra").on( "submit", function(e) {
                e.preventDefault();
                let url = $(this).attr('action');
                let data = $(this).serialize();
                var btn_confirmar_cambiar_contra = $("#btn_confirmar_cambiar_contra");
                var btn_cerrar_cambiar_contra = $("#btn_cerrar_cambiar_contra");
                var input_actual_password = $("#actual_password");
                var input_new_password_1 = $("#new_password_1");
                var input_new_password_2 = $("#new_password_2");
                var msg_alerts_mala_contrasena = $("#msg_alerta_actual_error");
                var msg_alerts_mala_doble_contra = $("#msg_alerta_doble_error");
                var msg_alerts_ok = $("#msg_alerta_ok");
                btn_confirmar_cambiar_contra.attr('disabled', 'disabled');
                btn_confirmar_cambiar_contra.html('Guardando {{ ux_icon('fa6-solid:spinner', {height: '16px', width: '16px', 'class': 'fa-pulse'}) }}');
                $.ajax({
                    url: url,
                    data: data,
                    type: 'POST',
                    cache: false,
                    success: function (resp) {
                        if (resp.status) {
                            setTimeout(function() {
                                msg_alerts_ok.fadeIn();
                                setTimeout(function() {
                                    btn_cerrar_cambiar_contra.click();
                                    input_actual_password.val('');
                                    input_new_password_1.val('');
                                    input_new_password_2.val('');
                                    btn_confirmar_cambiar_contra.prop('disabled', false);
                                    btn_confirmar_cambiar_contra.html('Cambiar contraseña {{ ux_icon('carbon:password', {height: '16px', width: '16px', 'aria-hidden': true}) }}');
                                    msg_alerts_ok.hide();
                                    msg_alerts_mala_doble_contra.hide();
                                    msg_alerts_mala_contrasena.hide();
                                }, 5000);
                            }, 500);
                        } else {
                            input_actual_password.val('');
                            input_new_password_1.val('');
                            input_new_password_2.val('');
                            btn_confirmar_cambiar_contra.prop('disabled', false);
                            btn_confirmar_cambiar_contra.html('Cambiar contraseña {{ ux_icon('carbon:password', {height: '16px', width: '16px', 'aria-hidden': true}) }}');
                            msg_alerts_mala_contrasena.fadeIn();
                            setTimeout(function() {
                                msg_alerts_mala_contrasena.fadeOut();
                            }, 5000);
                        }
                    },
                    error: function (xhr, status) {
                        console.error('Error al guardar cambios');
                    },
                });
            });
            $(document).find("#form_modificacion").on( "submit", function(e) {
                e.preventDefault();
                let url = $(this).attr('action');
                let data = $(this).serialize();
                var btn_confirmar_mod = $("#btn_confirmar_mod");
                var btn_texto_mod = $("#modificacion");
                var btn_cerrar_mod = $("#btn_cerrar_modi");
                btn_confirmar_mod.attr('disabled', 'disabled');
                btn_confirmar_mod.html('Guardando {{ ux_icon('fa6-solid:spinner', {height: '16px', width: '16px', 'class': 'fa-pulse'}) }}');
                $.ajax({
                    url: url,
                    data: data,
                    type: 'POST',
                    cache: false,
                    success: function (resp) {
                        setTimeout(function () {
                            btn_cerrar_mod.click();
                            setTimeout(function () {
                                btn_texto_mod.val('');
                                btn_confirmar_mod.prop('disabled', false);
                                btn_confirmar_mod.html('Pedir cambios {{ ux_icon('ph:list-star', {height: '16px', width: '16px', 'aria-hidden': true}) }}');
                            }, 100);
                        }, 500);
                    },
                    error: function (xhr, status) {
                        console.error('Error al guardar cambios');
                    },
                });
            });
        });
    </script>
{% endblock %}
{% block modals %}
    <div class="modal fade" id="cambiar_contra_modal" tabindex="-1" aria-labelledby="cambiar_contra_modal_label" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered modal-sm">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="cambiar_contra_modal_label">Cambiar contraseña</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close" id="btn_cerrar_cambiar_contra"></button>
                </div>
                <div class="modal-body">
                    <form id="form_cambiar_contra" action="{{ path('app_ajax_cambiar_contrasena') }}" method="POST">
                        <div id="msg_alerta_actual_error" style="display: none;">
                            <div class="alert alert-danger text-center">
                                Las contraseñas no coinciden.
                            </div>
                        </div>
                        <div id="msg_alerta_doble_error" style="display: none;">
                            <div class="alert alert-danger text-center">
                                Las contraseñas no coinciden.
                            </div>
                        </div>
                        <div id="msg_alerta_ok" style="display: none;">
                            <div class="alert alert-success text-center">
                                ¡Se cambió la contraseña exitosamente!
                            </div>
                        </div>
                        {% if app.user.tempPass == 0 %}
                            <label for="actual_password">Contraseña actual</label>
                            <input type="password" name="actual_password" id="actual_password" class="form-control" autocomplete="current-password" required>
                        {% endif %}
                        <label for="new_password_1">Nueva contraseña</label>
                        <input type="password" name="new_password_1" id="new_password_1" class="form-control" autocomplete="new-password" placeholder="Nueva contraseña" required>
                        <input type="password" name="new_password_2" id="new_password_2" class="form-control" autocomplete="new-2-password" placeholder="Repite la nueva contraseña" required>
                        <div class="mt-2">
                            <button type="submit" class="btn btn-success btn-submit w-100" id="btn_confirmar_cambiar_contra">
                                Cambiar contraseña {{ ux_icon('carbon:password', {height: '16px', width: '16px', 'aria-hidden': true}) }}
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <div class="modal fade" id="pedir_cambios_modal" tabindex="-1" aria-labelledby="pedir_cambios_modal_label" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="pedir_cambios_modal_label">Pedir un cambio</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close" id="btn_cerrar_modi"></button>
                </div>
                <div class="modal-body">
                    <form id="form_modificacion" action="{{ path('app_profile_pedir_cambio') }}" method="POST">
                        <div class="mb-2">
                            <label for="modificacion" class="form-label">Si necesitas algún cambio, escribe aquí.</label>
                            <textarea id="modificacion" name="modificacion" class="form-control" placeholder="Escribe tu cambio alimenticio o de asistencia" required></textarea>
                        </div>
                        <div class="">
                            <button type="submit" class="btn btn-success btn-submit w-100" id="btn_confirmar_mod">
                                Pedir cambios {{ ux_icon('ph:list-star', {height: '16px', width: '16px', 'aria-hidden': true}) }}
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}