src/Entity/Persona.php
<?php

namespace App\Entity;

use App\Repository\PersonaRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: PersonaRepository::class)]
class Persona
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $nombre_completo = null;

    #[ORM\Column(length: 50)]
    private ?string $tipo = null;

    #[ORM\Column(length: 50, nullable: true)]
    private ?string $status = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $alergias = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $mesa_preferencia = null;

    #[ORM\ManyToOne(inversedBy: 'personas')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $user = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNombreCompleto(): ?string
    {
        return $this->nombre_completo;
    }

    public function setNombreCompleto(string $nombre_completo): static
    {
        $this->nombre_completo = $nombre_completo;

        return $this;
    }

    public function getTipo(): ?string
    {
        return $this->tipo;
    }

    public function setTipo(string $tipo): static
    {
        $this->tipo = $tipo;

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(?string $status): static
    {
        $this->status = $status;

        return $this;
    }

    public function getAlergias(): ?string
    {
        return $this->alergias;
    }

    public function setAlergias(?string $alergias): static
    {
        $this->alergias = $alergias;

        return $this;
    }

    public function getMesaPreferencia(): ?string
    {
        return $this->mesa_preferencia;
    }

    public function setMesaPreferencia(?string $mesa_preferencia): static
    {
        $this->mesa_preferencia = $mesa_preferencia;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): static
    {
        $this->user = $user;

        return $this;
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Matrimonio Vicente Catalina{% endblock %}</title>
        <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 128 128%22><text y=%221.2em%22 font-size=%2296%22>⚫️</text><text y=%221.3em%22 x=%220.2em%22 font-size=%2276%22 fill=%22%23fff%22>sf</text></svg>">
        <meta name="viewport" content="width=device-width, shrink-to-fit=yes, user-scalable=yes">
        <!-- Favicon para navegadores -->
        <link rel="icon" href="{{ asset('icons/favicon.ico') }}" type="image/x-icon">

        <!-- Favicon en formato SVG -->
        <link rel="icon" href="{{ asset('images/favicon/favicon.svg') }}" type="image/svg+xml">

        <!-- Iconos para dispositivos Apple -->
        <link rel="apple-touch-icon" href="{{ asset('images/favicon/apple-touch-icon.png') }}">

        <!-- Iconos para dispositivos Android -->
        <link rel="icon" sizes="96x96" href="{{ asset('images/favicon/favicon-96x96.png') }}">
        <link rel="icon" sizes="192x192" href="{{ asset('images/favicon/web-app-manifest-192x192.png') }}">
        <link rel="icon" sizes="512x512" href="{{ asset('images/favicon/web-app-manifest-512x512.png') }}">

        <!-- Archivo Web App Manifest -->
        <link rel="manifest" href="{{ asset('images/favicon/site.webmanifest') }}">
        {% block stylesheets %}
            {% block importmap %}{{ importmap('app') }}{% endblock %}
            <link rel="preconnect" href="https://fonts.gstatic.com">
            <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300;400;700&display=swap" rel="stylesheet">
            <link href="https://fonts.googleapis.com/css2?family=Sora:wght@500&display=swap" rel="stylesheet">
            <link href="https://fonts.googleapis.com/css2?family=Hahmlet&family=Inter:wght@550&family=Lora&display=swap" rel="stylesheet">
        {% endblock %}

        {% block javascriptsHead %}
        {% endblock %}
    </head>
    <body>
        {% block nav %}
            <header class="header pb-1">
                <h1 style="margin-bottom: 0;" class="mb-0">Comparte la felicidad de unir nuestras vidas en matrimonio</h1>
                <h5 style="color: #D4AF37;" class="mb-0"><i>Matrimonio Barrenechea Etchegaray</i></h5>
                <i>1 de Marzo 2025</i>
                <ul class="nav justify-content-center mb-1">
                    <li class="nav-item">
                        <a class="nav-link{% if pagina is defined and pagina == 'inicio' %} active{% endif %}"{% if pagina is defined and pagina == 'inicio' %} aria-current="page"{% endif %} href="{{ path('app_home') }}">Inicio</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link{% if pagina is defined and pagina == 'fotos' %} active{% endif %}"{% if pagina is defined and pagina == 'fotos' %} aria-current="page"{% endif %} href="{{ path('app_fotos') }}">Fotos y Videos</a>
                    </li>
                    {% if app.user %}
                        <li class="nav-item">
                            <a class="nav-link disabled" aria-disabled="true">
                                ¡Hola {{ app.user.personas[0].nombreCompleto }}!
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link{% if pagina is defined and pagina == 'perfil' %} active{% endif %}"{% if pagina is defined and pagina == 'perfil' %} aria-current="page"{% endif %} href="{{ path('app_profile') }}">Perfil</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ path('app_logout') }}">Cerrar Sesión</a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link{% if pagina is defined and pagina == 'login' %} active{% endif %}"{% if pagina is defined and pagina == 'login' %} aria-current="page"{% endif %} href="{{ path('app_login') }}">Iniciar Sesión</a>
                        </li>
                    {% endif %}
                </ul>
            </header>
        {% endblock %}
        <main>
            <div id="main_container" class="container-fluid" style="">
                {% block body %}
                {% endblock %}
            </div>
        </main>
        {% block modals %}
        {% endblock %}
        {% block javascripts %}
        {% endblock %}
    </body>
</html>